#!/bin/bash
#
# Run checkupdates and send a notification to desktop if
# updates are available.
#
# Author: Tomi Juntunen <erani@iki.fi>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if ! command -v checkupdates;
then
    echo "checkupdates not installed" >&2
    exit 1
fi

if ! command -v notify-send;
then
    echo "notify-send not installed" >&2
    exit 1
fi

checkupdates

ReturnCode=$?

if [[ "${ReturnCode}" = 0 ]];
then
    notify-send "Pacman" "Package updates available"
    exit 0
elif [[ "${ReturnCode}" = 1 ]];
then
    echo "Something went wrong" >&2
    exit 1
fi

echo "No updates available"
exit 0
