name: Default branch

on:
  push:
    branches:
      - main

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run shellcheck validation
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ./scripts
